### ISSUE TITLE
Better dependency declaration

### ISSUE THREAD

**Issue by dgomezg** [AxonIQ/bike-rental-quick-start#1]
Right now AxonFramework dependencies are defined at the root project level, that makes some modules like core-api to import all axonframework dependencies even though most of them are not used.

Wouldn't it be better to declare the axon-framework-bom at the root project level, and then declare the specific axonframework dependencies in each of the modules?

**Comment by dgomezg** [comment]
That way it will also enable the "Building a Bike Rental application tutorial" to explain how to use the axon-framework bom.

**Comment by smcvb** [comment]
This sounds like a fine adjustment to me, @dgomezg :+1:
